### ISSUE TITLE
showdown version

### ISSUE THREAD

**Issue by andreineculau** [millermedeiros/mdoc#15]
Would be good to switch between the GFMarkdown and the pure Markdown.
One annoying thing is automatic-links which makes it impossible to have

[http://google.com](http://localhost)
meaning <a href="http://localhost">http://google.com</a>

because the content of the A tag will be replaced with another A tag with href http://google.com

**Comment by Kreozot** [comment]
Look like this issue can be closed since now we have an option to use another markdown parser.
