### ISSUE TITLE
Providing an extended context to handlebars for advanced template?

### ISSUE THREAD

**Issue by jourdain** [millermedeiros/mdoc#38]
I'm currently investigating tools for documented our code base and mdoc seems to have everything that I care about. Except that I would love to provide an extended context to the handlebars templates.

The reason behind that is to generate a unique custom template across a various set of projects that belong to the same family while keeping some flexibility regarding some labels/lists/links/etc. And while we are getting helper access to handlebars, we are missing some control to the input context.

So I was wondering if I add a new optional entry into the configuration (ctx), would you be ok with that?Then I would simply add a ctx argument from the config.ctx to each compiled template.

Let me know if that seems reasonable, and if so, I'll do a pull request.

Thanks,

Seb

**Comment by millermedeiros** [comment]
context seems like an useful feature. thanks for the pull request (#39)

**Comment by millermedeiros** [comment]
@eddiemonge is helping maintaining this project but I decided to merge it since change was simple and will increase flexibility.
